/*DROP TABLE IF EXISTS SERVER_AUDIT_LOG;*/

CREATE TABLE SERVER_AUDIT_LOG (
    AUDIT_TIMESTAMP VARCHAR(17) NOT NULL COMMENT 'timestamp',
    AUDIT_SERVERHOST VARCHAR(15) NOT NULL COMMENT 'serverhost',
    AUDIT_USERNAME VARCHAR(20) NOT NULL COMMENT 'username',
    AUDIT_HOST VARCHAR(20) NOT NULL COMMENT 'host',
    AUDIT_CONNECTIONID VARCHAR(11) NOT NULL COMMENT 'connectionid',
    AUDIT_QUERYID VARCHAR(15) NOT NULL COMMENT 'queryid',
    AUDIT_OPERATION VARCHAR(15) NOT NULL COMMENT 'operation',
    AUDIT_DATABASE VARCHAR(10) NULL COMMENT 'database',
    AUDIT_OBJECT TEXT NULL COMMENT 'object',
    AUDIT_RETCODE INT NOT NULL COMMENT 'retcode',
    INDEX(AUDIT_TIMESTAMP),
    INDEX(AUDIT_CONNECTIONID),
    INDEX(AUDIT_QUERYID)
) COMMENT = 'server audit log';


/*DROP TABLE IF EXISTS SERVER_AUDIT_MASTER;*/

CREATE TABLE SERVER_AUDIT_MASTER (
    CONNECTION_ID INT(11) UNSIGNED NOT NULL COMMENT '커넥션 ID',
    USER_NAME VARCHAR(20) NOT NULL COMMENT '사용자 ID',
    USER_HOST VARCHAR(20) NOT NULL COMMENT '사용자 IP',
    DATABASE_NAME VARCHAR(20) NULL COMMENT '데이터베이스 명',
    CONNECT_TIMESTAMP VARCHAR(17) NULL COMMENT '접속시간',
    DISCONNECT_TIMESTAMP VARCHAR(17) NULL COMMENT '종료시간',
    PRIMARY KEY (CONNECTION_ID)
) COMMENT = 'server audit log master';

/*DROP TABLE IF EXISTS PRIVATE_POLICY_HIST;*/

CREATE TABLE PRIVATE_POLICY_HIST (
    CONNECTION_ID INT(11) UNSIGNED NOT NULL COMMENT '커넥션 ID',
    QUERY_ID DECIMAL(15) NOT NULL COMMENT '쿼리 ID',
    START_TIMESTAMP VARCHAR(17) NULL COMMENT '쿼리 실행 시작 시간',
    END_TIMESTAMP VARCHAR(17) NULL COMMENT '쿼리 실행 종료 시간',
    QUERY TEXT NULL COMMENT '쿼리',
    POLICY_COUNT INT COMMENT '개인정보조회수',
    PRIMARY KEY (CONNECTION_ID, QUERY_ID),
    CONSTRAINT FOREIGN KEY (CONNECTION_ID) REFERENCES SERVER_AUDIT_MASTER (CONNECTION_ID)
) COMMENT='개인정보 조회 이력';

/*DROP TABLE IF EXISTS INCOMPLETE_QUERY;*/

CREATE TABLE INCOMPLETE_QUERY (
    CONNECTION_ID INT(11) UNSIGNED NOT NULL COMMENT '커넥션 ID',
    START_TIMESTAMP VARCHAR(17) NULL COMMENT '쿼리 실행 시작 시간',
    POLICY_COUNT INT COMMENT '개인정보조회수',
    PRIMARY KEY (CONNECTION_ID),
    CONSTRAINT FOREIGN KEY (CONNECTION_ID) REFERENCES SERVER_AUDIT_MASTER (CONNECTION_ID)
) COMMENT='미완료 쿼리 임시 저장';
